version: 0.2

phases:
  install:
    commands:
      - echo "No install step needed for plain HTML/JS"

  build:
    commands:
      - echo "No build step needed for plain HTML/JS"

artifacts:
  base-directory: frontend
  files:
    - '**/*'
